name: Run Python Script Every 5 min

on:
  schedule:
    - cron: "00 1 * * *"   # every hour, at minute 0 (UTC)
  workflow_dispatch:       # manual trigger
  push:
    branches:
      - dev              # run workflow only when code is on dev branch

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run script
        run: python fetch_and_push_news.py
